#pragma kernel CSMain

float deltaTime;
RWStructuredBuffer<float2> positionBuffer;
RWStructuredBuffer<float2> velocityBuffer;

[numthreads(256,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    velocityBuffer[id.x].y -= 0.98 * deltaTime;
    positionBuffer[id.x] += velocityBuffer[id.x] * deltaTime;
    
    if (positionBuffer[id.x].y < -5)
    {
        velocityBuffer[id.x].y *= -0.5;
        positionBuffer[id.x].y = -5;

    }
}
